# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/tale"
url:            "https://www.tmshkr.com"

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
